### ISSUE TITLE
CredentialsProvider fallback

### ISSUE THREAD

**Issue by meticoeus** [kohesive/vertx-sqs#2]
Why is ProfileCredentialsProvider the fallback instead of DefaultAWSCredentialsProviderChain, which will reference the profile location as part of the chain?

DefaultAWSCredentialsProviderChain also includes InstanceProfileCredentialsProvider for easier configuration when deploying to EC2.

**Comment by giurim** [comment]
Because ProfileCredentialsProvider is not always part of the
DefaultAWSCredentialsProviderChain. It depends on the AWS lib version.

2016-04-10 4:38 GMT+02:00 meticoeus <notifications@github.com>:

> Why is ProfileCredentialsProvider the fallback instead of
> DefaultAWSCredentialsProviderChain, which will reference the profile
> location as part of the chain?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Collokia/vertx-sqs/issues/2>
>



-- 
--
Móra György

**Comment by apatrida** [comment]
We typically avoid environment variables and system properties so place a safe fallback that does not use those.  Did you have a suggested difference, send a PR and I'll gladly look at it.

**Comment by stoccoPismo** [comment]
I have the same problem, can we use DefaultAWSCredentialsProviderChain() instead of the ProfileCredentialsProvider() method in the fallback? It is more secure than using accesskeys or aws configuration files in ec2.  Please :)

**Comment by apatrida** [comment]
Released in BETA-02
