### ISSUE TITLE
Please upload this artifact to maven central or similar

### ISSUE THREAD

**Issue by PatrickHuetter** [kohesive/vertx-sqs#3]
It would be fine to use this artifact as maven / gradle dependency.

**Comment by PatrickHuetter** [comment]
Any news on this?

**Comment by leosilvadev** [comment]
@apatrida @brainoutsource no plans for that?

**Comment by hasmikhail** [comment]
ping, would love to be able to use this via dependencies.  thanks in advance!

**Comment by apatrida** [comment]
yes, I can do a release to maven or bintray shortly, will move this yo our
open-source repos...

**Comment by apatrida** [comment]
This has moved to Kohesive to be maintained, updated to latest versions, and released to Maven central.
